# SPDX-License-Identifier: Apache-2.0
# Copyright 2022-present Open Networking Foundation

name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.3
          working-directory: pkg/pfcpsim
          args: -v --config ../../.golangci.yml
